# Generated by Django 4.2.14 on 2024-07-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=True)),
                ('phone', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('attachment', models.BooleanField(default=True)),
                ('link', models.BooleanField(default=True)),
                ('date_time', models.BooleanField(default=True)),
                ('time_placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_management', to='contract.contract')),
                ('inquiry_types', models.ManyToManyField(related_name='inquiry_managements', to='inquiry.inquirytype')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='생성일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('modified', models.DateField(auto_now=True, verbose_name='수정일자')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='폰번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('title', models.CharField(max_length=200, verbose_name='문의 제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='파일')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='문의 타입')),
                ('link', models.URLField(blank=True, null=True, verbose_name='링크')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='시간')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('param1', models.CharField(blank=True, max_length=255, null=True, verbose_name='파라미터1')),
                ('param2', models.CharField(blank=True, max_length=255, null=True, verbose_name='파라미터2')),
                ('param3', models.CharField(blank=True, max_length=255, null=True, verbose_name='파라미터3')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='contract.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
