# Generated by Django 4.2.14 on 2024-07-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='file',
            field=models.URLField(blank=True, null=True, verbose_name='파일 링크'),
        ),
    ]
