# Generated by Django 4.2.14 on 2024-07-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='폰번호'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='문의 제목'),
        ),
    ]
