# Generated by Django 4.0.10 on 2024-12-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_alter_inquiry_email_alter_inquiry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiry.inquirytype'),
        ),
    ]
