# Generated by Django 4.2.14 on 2024-07-23 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='생성일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('modified', models.DateField(auto_now=True, verbose_name='수정일자')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('subscription_consent', models.BooleanField(default=False, verbose_name='구독 동의')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='마케팅 동의')),
                ('personal_info_consent', models.BooleanField(default=False, verbose_name='개인정보 동의')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
