# Generated by Django 4.2.14 on 2024-07-24 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='생성일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('modified', models.DateField(auto_now=True, verbose_name='수정일자')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('company_name', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 기간')),
                ('expiration_date', models.DateField(verbose_name='계약 만료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
