name: Django CI - Build, Push Docker Image -> Update ECS Service

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ECR_REPOSITORY: ${{ secrets.ECR }}
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build, Push Docker Image, and Update ECS Service
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg ENVIRONMENT=${{ secrets.ARG_ENVIRONMENT }} --build-arg ACCESS_KEY=${{ secrets.ARG_AWS_ACCESS_KEY }} --build-arg SECRET_KEY=${{ secrets.ARG_AWS_SECRET_KEY }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Update ECS service
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
        ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
        ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
        ECR_REPOSITORY: ${{ secrets.ECR }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION > task-def.json
        jq --arg IMAGE "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG" \
           '.taskDefinition.containerDefinitions[0].image = $IMAGE' task-def.json > new-task-def.json
        jq 'del(.taskDefinition.status, .taskDefinition.taskDefinitionArn, .taskDefinition.requiresAttributes, .taskDefinition.compatibilities, .taskDefinition.revision, .taskDefinition.registeredAt, .taskDefinition.registeredBy)' \
           new-task-def.json > stripped-task-def.json
        NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://stripped-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')

        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $NEW_TASK_DEFINITION_ARN

        aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE
